<a href="https://colab.research.google.com/github/radhakrish-venkat/learn/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install numpy

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

In [20]:
print(arr)
result = (arr * 2)
result = result.reshape(2,3)
print(result)

print(result[0:1, 0:3])

[1 2 3 4 5 6]
[[ 2  4  6]
 [ 8 10 12]]
[[2 4 6]]


In [24]:
arr = np.array(range(9))
arr = arr.reshape(3,3)
arr = arr[:, np.newaxis]
print(arr)

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]
